// Copied from travel-amigo/data/places.ts (Phase 0 mock data → DB seed).
import type { Place } from "./types";

/**
 * Mock Sri Lanka places data.
 *
 * Costs are *estimated* figures in LKR and reflect approximate 2024–2025
 * traveller prices. They are intentionally rounded and should be treated as
 * guidance only — not as guaranteed prices.
 *
 * 0 = free entry.
 */
export const places: Place[] = [
  // ═══════════════════════════════════════════════════════════════════════
  //  ELLA
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: "ella-nine-arch",
    name: "Nine Arch Bridge",
    destination: "ella",
    category: "photography",
    tags: ["iconic", "colonial", "train", "instagram"],
    shortDescription:
      "Sri Lanka's most photographed railway viaduct, built from stone and brick during the British colonial era. Watch vintage blue trains roll slowly across the arches.",
    estimatedVisitDurationMinutes: 60,
    estimatedCostLkr: 0,
    bestTimeToVisit: "Early morning (6–8 am) or around 8:30 am / 2:45 pm train passage",
    travelTip: "Check the train timetable at Ella station the evening before so you can time your visit perfectly.",
    latitude: 6.8795,
    longitude: 81.0597,
    gradientPlaceholder: "from-emerald-400 to-teal-600",
    suitableFor: ["budget", "balanced", "premium"],
    interests: ["nature", "photography"],
  },
  {
    id: "ella-little-adams-peak",
    name: "Little Adam's Peak",
    destination: "ella",
    category: "nature",
    tags: ["hike", "views", "morning", "easy"],
    shortDescription:
      "A gentle 45-minute hike through tea plantations to a ridge with panoramic views of the Ella Gap and surrounding misty mountains.",
    estimatedVisitDurationMinutes: 120,
    estimatedCostLkr: 0,
    bestTimeToVisit: "Early morning (6–9 am) before cloud cover rolls in",
    travelTip: "Start before 7 am for the clearest skies and cooler temperatures. Wear grip shoes — paths can be muddy.",
    latitude: 6.8716,
    longitude: 81.0484,
    gradientPlaceholder: "from-green-400 to-emerald-600",
    suitableFor: ["budget", "balanced", "premium"],
    interests: ["nature", "adventure", "photography"],
  },
  {
    id: "ella-rock",
    name: "Ella Rock",
    destination: "ella",
    category: "adventure",
    tags: ["hike", "challenging", "views", "tea estates"],
    shortDescription:
      "A more demanding 3–4 hour return hike along railway tracks and forest trails, rewarded with sweeping views across the Ella ridge and Rawana Falls valley.",
    estimatedVisitDurationMinutes: 240,
    estimatedCostLkr: 0,
    bestTimeToVisit: "Early morning; avoid rainy season (Oct–Nov)",
    travelTip: "Bring at least 1.5 litres of water and a packed breakfast. The trail is unmarked in places — a local guide (~LKR 1,500) is worthwhile.",
    latitude: 6.8670,
    longitude: 81.0424,
    gradientPlaceholder: "from-teal-500 to-green-700",
    suitableFor: ["budget", "balanced"],
    interests: ["adventure", "nature", "photography"],
  },
  {
    id: "ella-ravana-falls",
    name: "Ravana Falls",
    destination: "ella",
    category: "nature",
    tags: ["waterfall", "roadside", "swimming", "legend"],
    shortDescription:
      "One of the widest waterfalls in Sri Lanka, cascading 25 metres down a rocky cliff face just a short tuk-tuk ride from Ella town. Linked to the Ramayana legend.",
    estimatedVisitDurationMinutes: 45,
    estimatedCostLkr: 0,
    bestTimeToVisit: "Morning or after rainfall for fuller flow",
    travelTip: "Swimming is possible in the pool at the base — bring a change of clothes. It gets crowded on weekends.",
    latitude: 6.8531,
    longitude: 81.0424,
    gradientPlaceholder: "from-blue-400 to-teal-500",
    suitableFor: ["budget", "balanced", "premium"],
    interests: ["nature", "photography", "family"],
  },
  {
    id: "ella-tea-factory-tour",
    name: "Uva Halpewatte Tea Factory",
    destination: "ella",
    category: "culture",
    tags: ["tea", "factory", "tasting", "education"],
    shortDescription:
      "A working tea factory nestled in the hills above Ella offering guided tours of the full tea-making process, from withering to drying, with a tasting included.",
    estimatedVisitDurationMinutes: 75,
    estimatedCostLkr: 500,
    bestTimeToVisit: "Morning (8 am–12 pm) when production is active",
    travelTip: "The factory runs on production days (Mon–Sat). Call ahead to confirm. The tasting room sells fresh estate tea cheaply.",
    latitude: 6.8820,
    longitude: 81.0310,
    gradientPlaceholder: "from-amber-300 to-emerald-500",
    suitableFor: ["budget", "balanced", "premium"],
    interests: ["culture", "food", "photography"],
  },
  {
    id: "ella-98-acres",
    name: "98 Acres Resort Viewpoint",
    destination: "ella",
    category: "viewpoint",
    tags: ["views", "sunset", "tea estate", "luxury"],
    shortDescription:
      "A hillside tea-estate resort whose terrace offers arguably the finest unobstructed view of the Ella Gap. Non-staying guests can enjoy high tea on the terrace.",
    estimatedVisitDurationMinutes: 90,
    estimatedCostLkr: 2500,
    bestTimeToVisit: "Late afternoon (4–6 pm) for golden-hour light over the gap",
    travelTip: "Reserve the terrace table in advance. The high-tea cost is offset by one of the most memorable views in hill country.",
    latitude: 6.8739,
    longitude: 81.0553,
    gradientPlaceholder: "from-amber-400 to-orange-500",
    suitableFor: ["balanced", "premium"],
    interests: ["relaxation", "photography", "food"],
  },
  {
    id: "ella-ella-gap-viewpoint",
    name: "Ella Gap Viewpoint",
    destination: "ella",
    category: "viewpoint",
    tags: ["free", "views", "town centre", "short walk"],
    shortDescription:
      "A short walk from Ella town's main street reveals a natural gap in the mountains framing a breathtaking view down to the southern lowlands.",
    estimatedVisitDurationMinutes: 30,
    estimatedCostLkr: 0,
    bestTimeToVisit: "Sunrise or late afternoon",
    travelTip: "Pairs perfectly with a coffee at one of the rooftop cafes on Ella's main road.",
    latitude: 6.8759,
    longitude: 81.0468,
    gradientPlaceholder: "from-sky-400 to-blue-600",
    suitableFor: ["budget", "balanced", "premium"],
    interests: ["nature", "photography", "relaxation"],
  },
  {
    id: "ella-rawana-cave",
    name: "Ravana Cave",
    destination: "ella",
    category: "culture",
    tags: ["legend", "cave", "ramayana", "hike"],
    shortDescription:
      "A Buddhist cave temple and significant site in the Ramayana legend, perched on a rocky hillside above Ella with guided meditation sessions at weekends.",
    estimatedVisitDurationMinutes: 60,
    estimatedCostLkr: 300,
    bestTimeToVisit: "Morning (8–11 am)",
    travelTip: "Dress respectfully — sarongs are available to borrow at the entrance. The short uphill path requires comfortable footwear.",
    latitude: 6.8574,
    longitude: 81.0471,
    gradientPlaceholder: "from-stone-400 to-amber-600",
    suitableFor: ["budget", "balanced", "premium"],
    interests: ["culture", "nature"],
  },
  {
    id: "ella-curd-and-treacle",
    name: "Curd & Treacle at Ella Market",
    destination: "ella",
    category: "food",
    tags: ["local food", "dessert", "market", "cheap"],
    shortDescription:
      "Buffalo curd drizzled with kithul treacle is Ella's signature street dessert. The local market stalls near the train station serve the freshest version.",
    estimatedVisitDurationMinutes: 30,
    estimatedCostLkr: 400,
    bestTimeToVisit: "Morning or after a hike",
    travelTip: "Kithul treacle is a natural palm syrup — try to buy a small bottle to take home. Bargain politely with stall holders.",
    latitude: 6.8761,
    longitude: 81.0495,
    gradientPlaceholder: "from-amber-200 to-yellow-400",
    suitableFor: ["budget", "balanced", "premium"],
    interests: ["food", "culture"],
  },

  // ═══════════════════════════════════════════════════════════════════════
  //  KANDY
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: "kandy-tooth-temple",
    name: "Temple of the Sacred Tooth Relic",
    destination: "kandy",
    category: "culture",
    tags: ["UNESCO", "temple", "buddhism", "relic", "iconic"],
    shortDescription:
      "One of the holiest Buddhist sites in the world, believed to enshrine a tooth of the Buddha. Stunning Kandyan architecture with daily puja ceremonies.",
    estimatedVisitDurationMinutes: 90,
    estimatedCostLkr: 2500,
    bestTimeToVisit:
      "Early morning puja (6:30 am) or evening puja (6:30 pm) for the most atmospheric experience",
    travelTip:
      "Dress modestly — covered shoulders and knees are mandatory. Remove shoes at the entrance. The camera fee is included in the ticket.",
    latitude: 7.2936,
    longitude: 80.6414,
    gradientPlaceholder: "from-amber-400 to-yellow-600",
    suitableFor: ["budget", "balanced", "premium"],
    interests: ["culture", "photography", "family"],
  },
  {
    id: "kandy-botanical-gardens",
    name: "Royal Botanical Gardens, Peradeniya",
    destination: "kandy",
    category: "nature",
    tags: ["gardens", "colonial", "orchids", "giant fig tree"],
    shortDescription:
      "One of Asia's finest botanical gardens covering 147 acres, featuring a massive Java fig tree, an orchid house, a fernery, and the royal palm avenue.",
    estimatedVisitDurationMinutes: 150,
    estimatedCostLkr: 2000,
    bestTimeToVisit: "Morning (8–11 am) year-round; orchid house peaks March–May",
    travelTip:
      "Hiring a bicycle at the entrance (~LKR 400) makes it easy to cover the full 147 acres without fatigue.",
    latitude: 7.2686,
    longitude: 80.5954,
    gradientPlaceholder: "from-green-400 to-teal-600",
    suitableFor: ["budget", "balanced", "premium"],
    interests: ["nature", "photography", "family", "relaxation"],
  },
  {
    id: "kandy-kandy-lake",
    name: "Kandy Lake & Cloud Wall Walk",
    destination: "kandy",
    category: "nature",
    tags: ["lake", "walk", "peaceful", "town"],
    shortDescription:
      "An artificial lake created in 1807, ringed by a lakeside promenade. The British-built 'cloud wall' on the southern bank is a popular sunset walk.",
    estimatedVisitDurationMinutes: 60,
    estimatedCostLkr: 0,
    bestTimeToVisit: "Sunset (5:30–7 pm)",
    travelTip: "Early morning is popular with local joggers. Bring a light jacket — the lakeside breeze gets cool after sunset.",
    latitude: 7.2923,
    longitude: 80.6427,
    gradientPlaceholder: "from-sky-400 to-blue-500",
    suitableFor: ["budget", "balanced", "premium"],
    interests: ["nature", "photography", "relaxation"],
  },
  {
    id: "kandy-kandyan-dance",
    name: "Kandyan Cultural Dance Show",
    destination: "kandy",
    category: "culture",
    tags: ["dance", "traditional", "drumming", "evening"],
    shortDescription:
      "A 75-minute evening performance showcasing traditional Kandyan dance, fire-walking, and acrobatics in an intimate open-air theatre.",
    estimatedVisitDurationMinutes: 90,
    estimatedCostLkr: 1800,
    bestTimeToVisit: "Nightly at 7:30 pm (doors open 7 pm)",
    travelTip:
      "Arrive early for front-row seating. The fire-walking finale — typically ~8:45 pm — is unmissable. Multiple venues exist; the YMBA hall is the most authentic.",
    latitude: 7.2935,
    longitude: 80.6361,
    gradientPlaceholder: "from-red-500 to-amber-600",
    suitableFor: ["budget", "balanced", "premium"],
    interests: ["culture", "photography", "family"],
  },
  {
    id: "kandy-bahiravokanda",
    name: "Bahiravokanda Buddha Statue",
    destination: "kandy",
    category: "viewpoint",
    tags: ["statue", "views", "hilltop", "free"],
    shortDescription:
      "A 27-metre white Buddha statue on a hilltop above the city, offering the best panoramic views of Kandy, the lake, and the surrounding tea hills.",
    estimatedVisitDurationMinutes: 60,
    estimatedCostLkr: 0,
    bestTimeToVisit: "Early morning for clear views; avoid midday haze",
    travelTip: "The 200-step climb is steep — wear comfortable shoes. The statue is lit up beautifully at night.",
    latitude: 7.2983,
    longitude: 80.6531,
    gradientPlaceholder: "from-stone-300 to-teal-400",
    suitableFor: ["budget", "balanced", "premium"],
    interests: ["culture", "photography", "nature"],
  },
  {
    id: "kandy-gem-museum",
    name: "National Gem & Jewellery Authority Museum",
    destination: "kandy",
    category: "culture",
    tags: ["gems", "museum", "sapphire", "education"],
    shortDescription:
      "Sri Lanka is the world's leading source of blue sapphires. This museum explains gem formation, mining, and grading with a collection of exceptional stones.",
    estimatedVisitDurationMinutes: 60,
    estimatedCostLkr: 500,
    bestTimeToVisit: "Any time; weekday mornings are less crowded",
    travelTip: "If you plan to buy gems or jewellery, only purchase from authorities registered with the National Gem & Jewellery Authority.",
    latitude: 7.2923,
    longitude: 80.6361,
    gradientPlaceholder: "from-blue-500 to-indigo-700",
    suitableFor: ["balanced", "premium"],
    interests: ["culture", "photography"],
  },
  {
    id: "kandy-spice-garden",
    name: "Pinnawela Spice Garden",
    destination: "kandy",
    category: "nature",
    tags: ["spices", "ayurveda", "garden", "tasting"],
    shortDescription:
      "A working spice and herbal garden where knowledgeable guides walk you through cinnamon, cardamom, pepper, and medicinal plants used in Ayurvedic treatments.",
    estimatedVisitDurationMinutes: 60,
    estimatedCostLkr: 300,
    bestTimeToVisit: "Morning or afternoon; open daily",
    travelTip: "Tastings and demonstrations are included in the entry price. Avoid pressure to buy products — they're generally cheaper at Kandy market.",
    latitude: 7.3027,
    longitude: 80.3864,
    gradientPlaceholder: "from-green-500 to-lime-600",
    suitableFor: ["budget", "balanced", "premium"],
    interests: ["nature", "food", "family"],
  },
  {
    id: "kandy-elephant-orphanage",
    name: "Pinnawela Elephant Orphanage",
    destination: "kandy",
    category: "wildlife",
    tags: ["elephants", "family", "conservation", "bathing"],
    shortDescription:
      "Home to over 80 elephants of all ages including babies, rescued from human-elephant conflict. Watch the twice-daily river bath from the bank.",
    estimatedVisitDurationMinutes: 120,
    estimatedCostLkr: 4000,
    bestTimeToVisit: "River bath: 10 am–noon and 2–4 pm",
    travelTip: "Choose riverside restaurants over direct contact experiences — mahout rides are not recommended by responsible tourism guides.",
    latitude: 7.3047,
    longitude: 80.3826,
    gradientPlaceholder: "from-stone-400 to-amber-500",
    suitableFor: ["balanced", "premium"],
    interests: ["nature", "family", "photography"],
  },
  {
    id: "kandy-local-food-tour",
    name: "Kandy City Market & Street Food Walk",
    destination: "kandy",
    category: "food",
    tags: ["local market", "street food", "spices", "cheap eats"],
    shortDescription:
      "The covered central market is a maze of spice vendors, hoppers, kottu roti cooks, and fresh-fruit stalls. A self-guided walk is entirely free.",
    estimatedVisitDurationMinutes: 90,
    estimatedCostLkr: 700,
    bestTimeToVisit: "Morning (7–10 am) when produce is freshest",
    travelTip: "Try a bowl of traditional kiri bath (milk rice) for breakfast — a local staple you won't find on tourist menus easily.",
    latitude: 7.2931,
    longitude: 80.6366,
    gradientPlaceholder: "from-orange-300 to-amber-500",
    suitableFor: ["budget", "balanced"],
    interests: ["food", "culture"],
  },

  // ═══════════════════════════════════════════════════════════════════════
  //  GALLE
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: "galle-fort",
    name: "Galle Dutch Fort",
    destination: "galle",
    category: "culture",
    tags: ["UNESCO", "colonial", "fort", "ramparts", "history"],
    shortDescription:
      "The best-preserved colonial sea fort in Asia, built by the Dutch in 1663 and still a living neighbourhood. Walk the 1.5 km ocean-facing ramparts at sunset.",
    estimatedVisitDurationMinutes: 180,
    estimatedCostLkr: 0,
    bestTimeToVisit: "Late afternoon (4–7 pm) for the golden sunset over the walls",
    travelTip: "The fort interior is fully walkable without an entry fee. Wear flat shoes — the rampart stones are uneven. Hire a local guide (~LKR 2,000) for deep history.",
    latitude: 6.0269,
    longitude: 80.2167,
    gradientPlaceholder: "from-amber-400 to-stone-600",
    suitableFor: ["budget", "balanced", "premium"],
    interests: ["culture", "photography", "relaxation"],
  },
  {
    id: "galle-rampart-walk",
    name: "Fort Rampart Sunset Walk",
    destination: "galle",
    category: "viewpoint",
    tags: ["sunset", "ocean", "free", "iconic"],
    shortDescription:
      "The 1.5 km perimeter wall of Galle Fort offers unobstructed views of the Indian Ocean as the sun dips below the horizon — a Sri Lanka bucket-list moment.",
    estimatedVisitDurationMinutes: 60,
    estimatedCostLkr: 0,
    bestTimeToVisit: "One hour before sunset",
    travelTip: "Arrive early and claim a good position on the Triton Bastion — the westernmost point. Local vendors sell king coconuts along the wall.",
    latitude: 6.0274,
    longitude: 80.2139,
    gradientPlaceholder: "from-orange-400 to-pink-600",
    suitableFor: ["budget", "balanced", "premium"],
    interests: ["photography", "relaxation", "beaches"],
  },
  {
    id: "galle-maritime-museum",
    name: "National Maritime Museum",
    destination: "galle",
    category: "culture",
    tags: ["museum", "maritime", "history", "colonial"],
    shortDescription:
      "Housed in a 17th-century Dutch warehouse inside the fort, this museum traces Galle's role as a trading hub with exhibits on shipwrecks, navigation, and coral conservation.",
    estimatedVisitDurationMinutes: 75,
    estimatedCostLkr: 600,
    bestTimeToVisit: "Morning (9 am–12 pm)",
    travelTip: "Combine with the Historical Mansion Museum next door for a full morning of fort history.",
    latitude: 6.0271,
    longitude: 80.2176,
    gradientPlaceholder: "from-blue-500 to-teal-700",
    suitableFor: ["balanced", "premium"],
    interests: ["culture", "photography"],
  },
  {
    id: "galle-fort-cafe-culture",
    name: "Fort Café Hopping",
    destination: "galle",
    category: "food",
    tags: ["cafes", "colonial buildings", "brunch", "coffee"],
    shortDescription:
      "Galle Fort hosts some of Sri Lanka's best cafés and restaurants in beautifully restored Dutch colonial buildings — perfect for lazy brunches and people-watching.",
    estimatedVisitDurationMinutes: 90,
    estimatedCostLkr: 2000,
    bestTimeToVisit: "Morning brunch (8–11 am) or afternoon tea (2–5 pm)",
    travelTip: "Pedlar Street and Church Street have the highest concentration. Café Arugam and The Pedlar's Inn are popular with both locals and travellers.",
    latitude: 6.0278,
    longitude: 80.2180,
    gradientPlaceholder: "from-amber-200 to-orange-400",
    suitableFor: ["balanced", "premium"],
    interests: ["food", "relaxation", "photography"],
  },
  {
    id: "galle-unawatuna-beach",
    name: "Unawatuna Beach",
    destination: "galle",
    category: "beach",
    tags: ["swimming", "snorkeling", "bay", "coconut palms"],
    shortDescription:
      "A sheltered crescent bay 6 km from Galle Fort with calm turquoise water ideal for swimming and snorkelling, lined with beachside restaurants and guesthouses.",
    estimatedVisitDurationMinutes: 240,
    estimatedCostLkr: 0,
    bestTimeToVisit: "November to April (calm south-west monsoon off-season)",
    travelTip: "Snorkel gear rental is available on the beach (~LKR 600/hr). The Japanese Peace Pagoda on the headland is a 15-minute walk and offers great views.",
    latitude: 6.0100,
    longitude: 80.2459,
    gradientPlaceholder: "from-cyan-400 to-blue-600",
    suitableFor: ["budget", "balanced", "premium"],
    interests: ["beaches", "nature", "relaxation", "family"],
  },
  {
    id: "galle-stilt-fishermen",
    name: "Koggala Stilt Fishermen",
    destination: "galle",
    category: "photography",
    tags: ["iconic", "fishermen", "sunrise", "cultural"],
    shortDescription:
      "The distinctive stilt fishermen balancing on small poles driven into the seabed are one of Sri Lanka's most iconic photographic subjects, practised on the coast near Koggala.",
    estimatedVisitDurationMinutes: 60,
    estimatedCostLkr: 500,
    bestTimeToVisit: "Early morning (6–8 am) or late afternoon; the fishermen request a small fee for photographs.",
    travelTip: "A small tip (~LKR 300–600) to photograph close-up is customary. Avoid sunrise-only tuk-tuk tours that may not encounter the fishermen at all.",
    latitude: 6.0020,
    longitude: 80.3137,
    gradientPlaceholder: "from-sky-300 to-teal-500",
    suitableFor: ["budget", "balanced", "premium"],
    interests: ["culture", "photography"],
  },
  {
    id: "galle-jungle-beach",
    name: "Jungle Beach",
    destination: "galle",
    category: "beach",
    tags: ["hidden", "snorkeling", "turtles", "quiet"],
    shortDescription:
      "A small, hidden beach accessible by a 10-minute walk through jungle from Unawatuna. Excellent snorkelling with turtle sightings and far fewer crowds.",
    estimatedVisitDurationMinutes: 180,
    estimatedCostLkr: 0,
    bestTimeToVisit: "Weekday mornings for minimal crowds",
    travelTip: "No sunbed rentals or vendors — bring your own water and snacks. Turtles feed near the rocks at the eastern end of the beach.",
    latitude: 6.0067,
    longitude: 80.2497,
    gradientPlaceholder: "from-green-400 to-cyan-600",
    suitableFor: ["budget", "balanced"],
    interests: ["beaches", "nature", "adventure", "relaxation"],
  },
  {
    id: "galle-lighthouse",
    name: "Galle Lighthouse",
    destination: "galle",
    category: "photography",
    tags: ["lighthouse", "ocean views", "historic", "fort"],
    shortDescription:
      "An 1848 lighthouse at the southernmost tip of Galle Fort, offering sea views in three directions and one of the fort's most photographed vantage points.",
    estimatedVisitDurationMinutes: 30,
    estimatedCostLkr: 0,
    bestTimeToVisit: "Sunset or sunrise",
    travelTip: "The lighthouse grounds are free to enter. Climbing inside is restricted, but the exterior and surrounding area provide excellent sunset compositions.",
    latitude: 6.0247,
    longitude: 80.2146,
    gradientPlaceholder: "from-stone-300 to-orange-400",
    suitableFor: ["budget", "balanced", "premium"],
    interests: ["photography", "culture", "relaxation"],
  },

  // ═══════════════════════════════════════════════════════════════════════
  //  NUWARA ELIYA
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: "ne-pedro-tea-estate",
    name: "Pedro Tea Estate & Factory",
    destination: "nuwara-eliya",
    category: "culture",
    tags: ["tea", "factory", "tasting", "plantation"],
    shortDescription:
      "One of Nuwara Eliya's oldest tea estates, Pedro offers guided factory tours showing the complete process from plucked leaf to finished Ceylon tea, with sampling.",
    estimatedVisitDurationMinutes: 90,
    estimatedCostLkr: 700,
    bestTimeToVisit: "Monday to Saturday morning (7 am–noon) when production is running",
    travelTip: "Buy a box of 'high-grown' estate tea at the factory shop — it's significantly fresher and cheaper than at tourist shops.",
    latitude: 6.9767,
    longitude: 80.7780,
    gradientPlaceholder: "from-green-400 to-emerald-700",
    suitableFor: ["budget", "balanced", "premium"],
    interests: ["culture", "food", "photography"],
  },
  {
    id: "ne-victoria-park",
    name: "Victoria Park",
    destination: "nuwara-eliya",
    category: "nature",
    tags: ["gardens", "birds", "flowers", "colonial"],
    shortDescription:
      "A well-maintained Victorian-era park in the town centre, famous for its seasonal flower displays and as a haven for rare migratory birds including the Kashmir flycatcher.",
    estimatedVisitDurationMinutes: 90,
    estimatedCostLkr: 300,
    bestTimeToVisit: "April and August for the best flower season; morning for bird-watching",
    travelTip: "Bring binoculars if you're a birder — the park hosts 20+ species rarely seen elsewhere in Sri Lanka.",
    latitude: 6.9693,
    longitude: 80.7753,
    gradientPlaceholder: "from-pink-300 to-green-500",
    suitableFor: ["budget", "balanced", "premium"],
    interests: ["nature", "relaxation", "photography", "family"],
  },
  {
    id: "ne-gregory-lake",
    name: "Lake Gregory",
    destination: "nuwara-eliya",
    category: "nature",
    tags: ["lake", "boating", "walks", "views"],
    shortDescription:
      "A serene artificial lake created in 1873, surrounded by hills, offering pedal-boating, speed-boat rides, and a pleasant lakeside walk with mountain views.",
    estimatedVisitDurationMinutes: 120,
    estimatedCostLkr: 500,
    bestTimeToVisit: "Morning or late afternoon; cool year-round",
    travelTip: "The paddle-boat rental (~LKR 800 for 30 min) is popular with families. The lakeside path is 3.2 km and takes about 50 minutes to complete.",
    latitude: 6.9552,
    longitude: 80.7742,
    gradientPlaceholder: "from-sky-300 to-teal-500",
    suitableFor: ["budget", "balanced", "premium"],
    interests: ["nature", "relaxation", "family", "photography"],
  },
  {
    id: "ne-horton-plains",
    name: "Horton Plains & World's End",
    destination: "nuwara-eliya",
    category: "adventure",
    tags: ["national park", "hike", "world's end", "cloud forest"],
    shortDescription:
      "A high-altitude patana grassland national park with a dramatic 870-metre escarpment at 'World's End'. The circular 9 km trail takes 3–4 hours.",
    estimatedVisitDurationMinutes: 240,
    estimatedCostLkr: 5000,
    bestTimeToVisit: "Before 10 am — clouds roll in after mid-morning obscuring the drop. Arrive at dawn for the best view.",
    travelTip: "Wear warm layers — temperatures drop to 10°C at 2,100 m elevation. The park entry is one of the most expensive in Sri Lanka but absolutely worth it.",
    latitude: 6.8092,
    longitude: 80.8019,
    gradientPlaceholder: "from-emerald-600 to-stone-500",
    suitableFor: ["balanced", "premium"],
    interests: ["nature", "adventure", "photography"],
  },
  {
    id: "ne-seetha-amman-temple",
    name: "Seetha Amman Temple",
    destination: "nuwara-eliya",
    category: "culture",
    tags: ["temple", "ramayana", "colourful", "stream"],
    shortDescription:
      "A brightly painted Hindu temple built at the site where Sita is believed to have been held captive in the Ramayana, alongside a sacred stream with vivid rock formations.",
    estimatedVisitDurationMinutes: 45,
    estimatedCostLkr: 0,
    bestTimeToVisit: "Morning puja (6–8 am) or evening (5–7 pm)",
    travelTip: "This is an active place of worship — observe respectfully and dress modestly. Photography of the main shrine is restricted.",
    latitude: 6.9311,
    longitude: 80.7872,
    gradientPlaceholder: "from-orange-400 to-red-600",
    suitableFor: ["budget", "balanced", "premium"],
    interests: ["culture", "photography"],
  },
  {
    id: "ne-tea-plantation-walk",
    name: "Tea Plantation Walk (Nuwara Eliya)",
    destination: "nuwara-eliya",
    category: "nature",
    tags: ["walk", "tea fields", "pluckers", "views"],
    shortDescription:
      "Self-guided or guided walks through the surrounding tea estates offer a ground-level view of tea plucking, with terraced emerald-green rows on every slope.",
    estimatedVisitDurationMinutes: 120,
    estimatedCostLkr: 0,
    bestTimeToVisit: "Morning (7–11 am) to watch tea pluckers at work",
    travelTip: "Ask your guesthouse for a recommended walking route — some estates welcome visitors, others do not. Never enter private estate land without permission.",
    latitude: 6.9720,
    longitude: 80.7840,
    gradientPlaceholder: "from-lime-400 to-green-600",
    suitableFor: ["budget", "balanced", "premium"],
    interests: ["nature", "photography", "relaxation"],
  },
  {
    id: "ne-hakgala-gardens",
    name: "Hakgala Botanical Gardens",
    destination: "nuwara-eliya",
    category: "nature",
    tags: ["botanical", "roses", "cool climate", "garden"],
    shortDescription:
      "A 27-hectare botanical garden at 1,745 m, originally established as a cinchona (quinine) plantation. Famous for its rose garden and cool-climate species.",
    estimatedVisitDurationMinutes: 120,
    estimatedCostLkr: 1200,
    bestTimeToVisit: "April–May for rose blooms; morning for best light",
    travelTip: "The rose garden is best photographed in soft morning light. Monkeys are common — don't leave food visible.",
    latitude: 6.9081,
    longitude: 80.8000,
    gradientPlaceholder: "from-rose-400 to-pink-600",
    suitableFor: ["budget", "balanced", "premium"],
    interests: ["nature", "photography", "relaxation", "family"],
  },
  {
    id: "ne-colonial-hill-club",
    name: "Hill Club Colonial Dinner",
    destination: "nuwara-eliya",
    category: "food",
    tags: ["colonial", "heritage", "dinner", "dress code"],
    shortDescription:
      "The Hill Club, built in 1876, admits non-members for dinner in its grand dining hall complete with fireplace, hunting trophies, and strict formal dress code — a time-warp experience.",
    estimatedVisitDurationMinutes: 120,
    estimatedCostLkr: 8000,
    bestTimeToVisit: "Dinner service (7–9:30 pm); reservations required",
    travelTip: "Men must wear a jacket and tie (both available to borrow at the door). Reserve at least two days in advance. The three-course set menu is classic British-colonial fare.",
    latitude: 6.9687,
    longitude: 80.7734,
    gradientPlaceholder: "from-stone-600 to-amber-700",
    suitableFor: ["premium"],
    interests: ["food", "culture", "relaxation"],
  },

  // ═══════════════════════════════════════════════════════════════════════
  //  COLOMBO
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: "colombo-galle-face-green",
    name: "Galle Face Green",
    destination: "colombo",
    category: "nature",
    tags: ["seafront", "promenade", "evening", "street food", "kites"],
    shortDescription:
      "A 500-metre oceanfront esplanade in the city centre — the perfect place to watch the sunset, fly a kite, and try local street snacks like isso wade (prawn fritters) and seeni sambol rolls.",
    estimatedVisitDurationMinutes: 90,
    estimatedCostLkr: 300,
    bestTimeToVisit: "Late afternoon and evening (4–8 pm) when breezes are pleasant",
    travelTip: "Isso wade stalls are clustered near the southern end. Bargain for the kite sellers' prices — it's expected.",
    latitude: 6.9170,
    longitude: 79.8445,
    gradientPlaceholder: "from-cyan-400 to-sky-600",
    suitableFor: ["budget", "balanced", "premium"],
    interests: ["food", "photography", "relaxation", "family"],
  },
  {
    id: "colombo-pettah-market",
    name: "Pettah Bazaar",
    destination: "colombo",
    category: "culture",
    tags: ["market", "chaotic", "local", "trade", "old town"],
    shortDescription:
      "Colombo's historic commercial district is a sensory overload of street vendors, gem shops, fabric stalls, and Dutch-colonial architecture — the most 'local' part of the city.",
    estimatedVisitDurationMinutes: 120,
    estimatedCostLkr: 0,
    bestTimeToVisit: "Weekday mornings (9 am–noon) when traders are most active",
    travelTip: "Keep your bag in front of you in the crowds. The covered Pettah Market and adjoining Main Street are the most interesting areas.",
    latitude: 6.9385,
    longitude: 79.8506,
    gradientPlaceholder: "from-amber-400 to-orange-600",
    suitableFor: ["budget", "balanced"],
    interests: ["culture", "photography", "food"],
  },
  {
    id: "colombo-gangaramaya",
    name: "Gangaramaya Buddhist Temple",
    destination: "colombo",
    category: "culture",
    tags: ["temple", "eclectic", "museum", "buddha"],
    shortDescription:
      "The most visited temple in Colombo blends Sri Lankan, Thai, Indian, and Chinese architectural styles and houses an extraordinary museum of religious artefacts, elephants, and oddities.",
    estimatedVisitDurationMinutes: 90,
    estimatedCostLkr: 300,
    bestTimeToVisit: "Morning puja (6:30–8 am) or anytime for the museum",
    travelTip:
      "Dress modestly and remove shoes at the entrance. The museum section (same ticket) is unexpectedly vast — allow at least 45 minutes for it.",
    latitude: 6.9164,
    longitude: 79.8557,
    gradientPlaceholder: "from-yellow-400 to-amber-600",
    suitableFor: ["budget", "balanced", "premium"],
    interests: ["culture", "photography"],
  },
  {
    id: "colombo-national-museum",
    name: "National Museum of Colombo",
    destination: "colombo",
    category: "culture",
    tags: ["museum", "history", "artefacts", "colonial"],
    shortDescription:
      "Sri Lanka's largest museum, founded in 1877, with 100,000+ artefacts spanning from ancient kingdoms to colonial rule — including the royal throne and regalia of the last Kandyan king.",
    estimatedVisitDurationMinutes: 120,
    estimatedCostLkr: 2000,
    bestTimeToVisit: "Thursday to Monday (closed Tuesdays); morning for smaller crowds",
    travelTip: "The natural history wing is often overlooked but contains impressive endemic species exhibits. Audio guides are available for an additional fee.",
    latitude: 6.9026,
    longitude: 79.8614,
    gradientPlaceholder: "from-stone-400 to-amber-600",
    suitableFor: ["budget", "balanced", "premium"],
    interests: ["culture", "photography", "family"],
  },
  {
    id: "colombo-independence-square",
    name: "Independence Square",
    destination: "colombo",
    category: "culture",
    tags: ["memorial", "architecture", "walking", "historical"],
    shortDescription:
      "The Independence Memorial Hall built in 1948 with Kandyan architectural touches, set in a peaceful park with fountains, walkways, and local joggers.",
    estimatedVisitDurationMinutes: 60,
    estimatedCostLkr: 0,
    bestTimeToVisit: "Morning or evening; light from the west makes the colonnade photogenic at sunrise.",
    travelTip: "The surrounding Viharamahadevi Park (formally Victoria Park) is great for a shaded walk before or after.",
    latitude: 6.8970,
    longitude: 79.8640,
    gradientPlaceholder: "from-stone-300 to-teal-500",
    suitableFor: ["budget", "balanced", "premium"],
    interests: ["culture", "photography", "relaxation"],
  },
  {
    id: "colombo-dutch-hospital",
    name: "Dutch Hospital Shopping Precinct",
    destination: "colombo",
    category: "food",
    tags: ["colonial", "restaurants", "shopping", "heritage"],
    shortDescription:
      "A 17th-century Dutch colonial hospital in the Colombo Fort precinct, sensitively restored into a lively cluster of restaurants, bars, and boutique shops.",
    estimatedVisitDurationMinutes: 120,
    estimatedCostLkr: 3000,
    bestTimeToVisit: "Lunch (12–2 pm) or dinner (6–10 pm)",
    travelTip: "Ministry of Crab (by Dharshan Munidasa) is located here — widely regarded as one of Asia's best seafood restaurants. Book weeks in advance.",
    latitude: 6.9341,
    longitude: 79.8438,
    gradientPlaceholder: "from-amber-300 to-stone-500",
    suitableFor: ["balanced", "premium"],
    interests: ["food", "culture", "photography"],
  },
  {
    id: "colombo-kelaniya-temple",
    name: "Kelaniya Raja Maha Vihara",
    destination: "colombo",
    category: "culture",
    tags: ["ancient temple", "frescos", "buddhism", "sacred"],
    shortDescription:
      "One of Sri Lanka's most sacred temples, visited by the Buddha himself according to legend. The painted murals depicting the Jataka tales are among the finest in the country.",
    estimatedVisitDurationMinutes: 90,
    estimatedCostLkr: 0,
    bestTimeToVisit: "Morning (6–9 am) for the freshest flowers and incense; quieter on weekdays",
    travelTip: "The painted interior is extraordinary — look up at the ceiling murals painted in the 1930s by artist Solias Mendis. Photography is usually permitted.",
    latitude: 6.9547,
    longitude: 79.9213,
    gradientPlaceholder: "from-orange-400 to-yellow-500",
    suitableFor: ["budget", "balanced", "premium"],
    interests: ["culture", "photography"],
  },
  {
    id: "colombo-barefoot-garden",
    name: "Barefoot Garden Café",
    destination: "colombo",
    category: "food",
    tags: ["café", "design", "boutique", "relaxed"],
    shortDescription:
      "A beloved Colombo institution: a lush garden café and craft boutique where Sri Lankan designers' textiles, books, and artwork are sold alongside excellent lunches and Sri Lankan sweets.",
    estimatedVisitDurationMinutes: 90,
    estimatedCostLkr: 2500,
    bestTimeToVisit: "Weekend brunch (9 am–1 pm) when the garden tables are most lively",
    travelTip: "The Saturday live jazz is a Colombo institution — arrive early because garden seating fills quickly. The fabric section sells outstanding handloom products.",
    latitude: 6.8963,
    longitude: 79.8619,
    gradientPlaceholder: "from-green-300 to-lime-500",
    suitableFor: ["balanced", "premium"],
    interests: ["food", "relaxation", "culture"],
  },
  {
    id: "colombo-viharamahadevi-park",
    name: "Viharamahadevi Park",
    destination: "colombo",
    category: "nature",
    tags: ["park", "family", "pagoda", "golden buddha"],
    shortDescription:
      "Colombo's largest public park with a striking golden Buddha, a children's play area, and tree-lined paths — a rare green lung in the busy city.",
    estimatedVisitDurationMinutes: 60,
    estimatedCostLkr: 0,
    bestTimeToVisit: "Early morning or evening when local families are out",
    travelTip: "The golden Buddha reflects beautifully at sunset. The park is well-lit at night and remains safe.",
    latitude: 6.9005,
    longitude: 79.8636,
    gradientPlaceholder: "from-yellow-300 to-green-500",
    suitableFor: ["budget", "balanced", "premium"],
    interests: ["nature", "relaxation", "family", "photography"],
  },
  {
    id: "colombo-taste-of-ceylon",
    name: "Taste of Ceylon Food Tour",
    destination: "colombo",
    category: "food",
    tags: ["street food", "hoppers", "kottu", "food tour"],
    shortDescription:
      "A self-guided food crawl through the Kollupitiya and Wellawatte neighbourhoods, sampling hoppers, kottu roti, pol sambol, and string hoppers at local joints.",
    estimatedVisitDurationMinutes: 180,
    estimatedCostLkr: 1500,
    bestTimeToVisit: "Evening (6–9 pm) when street food stalls come alive",
    travelTip: "Hopper vendors typically operate dinner hours only (5–10 pm). The famous Pillawoos is open 24/7 on RA De Mel Mawatha for kottu roti.",
    latitude: 6.8924,
    longitude: 79.8571,
    gradientPlaceholder: "from-red-400 to-amber-500",
    suitableFor: ["budget", "balanced"],
    interests: ["food", "culture", "adventure"],
  },
  {
    id: "colombo-cinnamon-life",
    name: "Cinnamon Life Waterfront",
    destination: "colombo",
    category: "viewpoint",
    tags: ["luxury", "waterfront", "views", "shopping", "spa"],
    shortDescription:
      "Sri Lanka's largest integrated resort — a 5-billion-dollar waterfront development with luxury hotel, rooftop bar, sky walk, casino, and a marina promenade.",
    estimatedVisitDurationMinutes: 120,
    estimatedCostLkr: 3000,
    bestTimeToVisit: "Evening for rooftop drinks and harbour views",
    travelTip: "The sky walk and observation deck offer Colombo's best 360° panorama. The rooftop bar is expensive but worth it for the sunset views.",
    latitude: 6.9275,
    longitude: 79.8440,
    gradientPlaceholder: "from-sky-500 to-indigo-700",
    suitableFor: ["premium"],
    interests: ["relaxation", "photography", "food"],
  },
];
